CREATE TABLE replay_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(20) NOT NULL,
    version integer NOT NULL DEFAULT 0,
    rule_id bigint NOT NULL,
    rule_revision integer NOT NULL,
    snapshot_schema_version integer NOT NULL,
    rule_snapshot jsonb NOT NULL,
    occurred_from timestamptz NOT NULL,
    occurred_to timestamptz NOT NULL,
    api_key_id bigint,
    warmup_from timestamptz NOT NULL,
    action_mode varchar(20) NOT NULL DEFAULT 'NO_ACTIONS',
    total_output_events bigint NOT NULL DEFAULT 0,
    total_materialized_events bigint NOT NULL DEFAULT 0,
    processed_output_events bigint NOT NULL DEFAULT 0,
    matched_events bigint NOT NULL DEFAULT 0,
    error_events bigint NOT NULL DEFAULT 0,
    last_committed_position bigint,
    lease_token varchar(36),
    lease_expires_at timestamptz,
    created_by varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    failure_category varchar(80),
    failure_message varchar(1000),
    CONSTRAINT replay_jobs_status_check CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT replay_jobs_action_mode_check CHECK (action_mode = 'NO_ACTIONS'),
    CONSTRAINT replay_jobs_range_check CHECK (occurred_from < occurred_to),
    CONSTRAINT replay_jobs_counts_check CHECK (
        total_output_events >= 0
        AND total_materialized_events >= 0
        AND processed_output_events >= 0
        AND matched_events >= 0
        AND error_events >= 0
    )
);

CREATE INDEX idx_replay_jobs_status_created
    ON replay_jobs (status, created_at, id);

CREATE TABLE replay_job_events (
    job_id bigint NOT NULL REFERENCES replay_jobs(id) ON DELETE CASCADE,
    position bigint NOT NULL,
    original_event_id bigint,
    type varchar(100) NOT NULL,
    source varchar(100) NOT NULL,
    occurred_at timestamptz NOT NULL,
    api_key_id bigint,
    original_event_time_status varchar(20),
    data jsonb NOT NULL,
    in_requested_range boolean NOT NULL,
    PRIMARY KEY (job_id, position),
    CONSTRAINT replay_job_events_status_check CHECK (
        original_event_time_status IS NULL
        OR original_event_time_status IN ('ON_TIME', 'LATE_ACCEPTED', 'TOO_LATE')
    )
);

CREATE INDEX idx_replay_job_events_job_range_position
    ON replay_job_events (job_id, in_requested_range, position);

CREATE TABLE replay_job_rule_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES replay_jobs(id) ON DELETE CASCADE,
    input_position bigint NOT NULL,
    occurred_at timestamptz NOT NULL,
    group_key varchar(500),
    value double precision,
    CONSTRAINT uk_replay_job_rule_events_job_position UNIQUE (job_id, input_position)
);

CREATE INDEX idx_replay_job_rule_events_job_group_occurred_position
    ON replay_job_rule_events (job_id, group_key, occurred_at, input_position);

CREATE TABLE replay_job_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES replay_jobs(id) ON DELETE CASCADE,
    input_position bigint NOT NULL,
    original_event_id bigint,
    type varchar(100) NOT NULL,
    source varchar(100) NOT NULL,
    occurred_at timestamptz NOT NULL,
    matched boolean NOT NULL,
    group_key varchar(500),
    aggregate_result jsonb,
    error_category varchar(80),
    completed_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_replay_job_outcomes_job_position UNIQUE (job_id, input_position)
);

CREATE INDEX idx_replay_job_outcomes_job_position
    ON replay_job_outcomes (job_id, input_position);

CREATE INDEX idx_replay_job_outcomes_job_matched_position
    ON replay_job_outcomes (job_id, matched, input_position);
