CREATE TABLE rabbitmq_connectors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_key varchar(80) NOT NULL UNIQUE,
    display_name varchar(100) NOT NULL,
    host varchar(255) NOT NULL,
    port integer NOT NULL,
    virtual_host varchar(255) NOT NULL,
    tls_enabled boolean NOT NULL,
    username varchar(255) NOT NULL,
    password_ciphertext bytea,
    password_nonce bytea,
    encryption_key_version integer,
    queue_name varchar(255) NOT NULL,
    dead_letter_exchange varchar(255) NOT NULL,
    dead_letter_routing_key varchar(255) NOT NULL,
    api_key_id bigint NOT NULL REFERENCES api_keys(id),
    enabled boolean NOT NULL DEFAULT false,
    max_body_bytes integer NOT NULL,
    retry_attempts integer NOT NULL,
    retry_initial_delay_ms bigint NOT NULL,
    retry_multiplier double precision NOT NULL,
    retry_max_delay_ms bigint NOT NULL,
    configuration_version bigint NOT NULL DEFAULT 1,
    last_tested_version bigint,
    last_tested_at timestamptz,
    last_test_succeeded boolean,
    last_test_error_category varchar(80),
    row_version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT rabbitmq_connectors_port_check CHECK (port BETWEEN 1 AND 65535),
    CONSTRAINT rabbitmq_connectors_body_limit_check CHECK (max_body_bytes BETWEEN 1 AND 10485760),
    CONSTRAINT rabbitmq_connectors_retry_attempts_check CHECK (retry_attempts BETWEEN 1 AND 20),
    CONSTRAINT rabbitmq_connectors_retry_initial_delay_check CHECK (retry_initial_delay_ms BETWEEN 0 AND 600000),
    CONSTRAINT rabbitmq_connectors_retry_multiplier_check CHECK (retry_multiplier >= 1 AND retry_multiplier <= 10),
    CONSTRAINT rabbitmq_connectors_retry_max_delay_check CHECK (retry_max_delay_ms BETWEEN 0 AND 3600000)
);

CREATE TABLE rabbitmq_message_receipts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_id bigint NOT NULL REFERENCES rabbitmq_connectors(id),
    queue_name varchar(255) NOT NULL,
    message_id varchar(255) NOT NULL,
    source_exchange varchar(255),
    routing_key varchar(255),
    api_key_id bigint NOT NULL REFERENCES api_keys(id),
    event_id bigint REFERENCES events(id) ON DELETE SET NULL,
    processed_at timestamptz NOT NULL,
    CONSTRAINT uk_rabbitmq_receipt_identity UNIQUE (connector_id, queue_name, message_id)
);

CREATE INDEX idx_rabbitmq_receipts_event ON rabbitmq_message_receipts (event_id);
CREATE INDEX idx_rabbitmq_receipts_processed ON rabbitmq_message_receipts (processed_at);

ALTER TABLE events ADD COLUMN ingestion_origin varchar(20) NOT NULL DEFAULT 'HTTP';
ALTER TABLE events ADD COLUMN rabbitmq_connector_id bigint REFERENCES rabbitmq_connectors(id);
ALTER TABLE events ADD CONSTRAINT events_ingestion_origin_check
    CHECK (ingestion_origin IN ('HTTP', 'RABBITMQ'));

CREATE INDEX idx_events_ingestion_origin_received
    ON events (ingestion_origin, received_at, id);
