ALTER TABLE replay_jobs
    ADD COLUMN attempt_count integer NOT NULL DEFAULT 0,
    ADD COLUMN retryable boolean NOT NULL DEFAULT false,
    ADD COLUMN paused_at timestamptz,
    ADD COLUMN cancelled_at timestamptz,
    ADD COLUMN last_retried_at timestamptz;

ALTER TABLE replay_jobs
    DROP CONSTRAINT replay_jobs_status_check;

ALTER TABLE replay_jobs
    ADD CONSTRAINT replay_jobs_status_check CHECK (
        status IN (
            'QUEUED', 'RUNNING', 'PAUSE_REQUESTED', 'PAUSED',
            'CANCEL_REQUESTED', 'CANCELLED', 'COMPLETED', 'FAILED'
        )
    );

ALTER TABLE replay_jobs
    ADD CONSTRAINT replay_jobs_attempt_count_check CHECK (attempt_count >= 0);

CREATE INDEX idx_replay_jobs_status_updated
    ON replay_jobs (status, updated_at, id);

CREATE INDEX idx_replay_jobs_rule_revision_created
    ON replay_jobs (rule_id, rule_revision, created_at, id);

CREATE INDEX idx_replay_jobs_created_by_created
    ON replay_jobs (created_by, created_at, id);

CREATE TABLE replay_job_transitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES replay_jobs(id) ON DELETE CASCADE,
    transition_sequence bigint NOT NULL,
    from_status varchar(30),
    to_status varchar(30) NOT NULL,
    action varchar(40) NOT NULL,
    actor varchar(100) NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    reason varchar(80),
    transitioned_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_replay_job_transitions_job_sequence
        UNIQUE (job_id, transition_sequence),
    CONSTRAINT replay_job_transitions_attempt_check CHECK (attempt_count >= 0)
);

CREATE INDEX idx_replay_job_transitions_job_time
    ON replay_job_transitions (job_id, transitioned_at, id);
