ALTER TABLE rules DROP CONSTRAINT IF EXISTS rules_action_check;
ALTER TABLE rules ADD CONSTRAINT rules_action_check
    CHECK (action IN ('LOG', 'WEBHOOK', 'EMAIL', 'SMS'));

ALTER TABLE event_rule_outcomes DROP CONSTRAINT IF EXISTS event_rule_outcomes_action_outcome_check;
ALTER TABLE event_rule_outcomes ADD CONSTRAINT event_rule_outcomes_action_outcome_check
    CHECK (action_outcome IN (
        'LOG_ONLY', 'WEBHOOK_QUEUED', 'WEBHOOK_SUPPRESSED',
        'EMAIL_QUEUED', 'EMAIL_SUPPRESSED', 'EMAIL_FAILED',
        'SMS_QUEUED', 'SMS_SUPPRESSED', 'SMS_FAILED'
    ));

ALTER TABLE rules ADD COLUMN IF NOT EXISTS notification_destination_id bigint;
ALTER TABLE rules ADD COLUMN IF NOT EXISTS notification_template_id bigint;
ALTER TABLE rules ADD COLUMN IF NOT EXISTS notification_recipient_mode varchar(20);
ALTER TABLE rules ADD COLUMN IF NOT EXISTS notification_recipients jsonb;
ALTER TABLE rules ADD COLUMN IF NOT EXISTS notification_recipient_field varchar(200);

CREATE TABLE notification_destinations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_key varchar(36) NOT NULL UNIQUE,
    display_name varchar(100) NOT NULL,
    channel varchar(10) NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    provider varchar(40) NOT NULL,
    configuration jsonb NOT NULL,
    credential_ciphertext bytea,
    credential_nonce bytea,
    encryption_key_version integer,
    enabled boolean NOT NULL,
    last_tested_at timestamptz,
    last_test_succeeded boolean,
    last_test_error_category varchar(80),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE notification_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    channel varchar(10) NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    version integer NOT NULL,
    subject_template text,
    text_template text NOT NULL,
    html_template text,
    css_template text,
    active boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uk_notification_templates_name_version UNIQUE (name, version)
);

CREATE TABLE notification_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES events(id),
    rule_id bigint,
    rule_revision integer NOT NULL DEFAULT 1,
    rule_name varchar(100) NOT NULL,
    destination_id bigint,
    channel varchar(10) NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    provider varchar(40) NOT NULL,
    message_snapshot jsonb NOT NULL,
    scope_key varchar(500) NOT NULL,
    trigger_mode varchar(20) NOT NULL CHECK (trigger_mode IN ('EVERY_MATCH', 'EDGE', 'ONCE_PER_WINDOW')),
    window_start timestamptz,
    deduplication_key varchar(1000) NOT NULL UNIQUE,
    status varchar(30) NOT NULL CHECK (status IN (
        'PENDING', 'PROCESSING', 'RETRY_SCHEDULED', 'SUBMITTED', 'DELIVERED',
        'DEAD_LETTER', 'TEMPLATE_RENDER_ERROR')),
    attempt_count integer NOT NULL,
    next_attempt_at timestamptz NOT NULL,
    last_attempt_at timestamptz,
    submitted_at timestamptz,
    delivered_at timestamptz,
    provider_message_id varchar(255),
    last_error text,
    manually_retried_at timestamptz,
    lease_token varchar(36),
    lease_expires_at timestamptz,
    cooldown_seconds integer,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE INDEX idx_notification_outbox_status_next_attempt
    ON notification_outbox (status, next_attempt_at, id);
CREATE INDEX idx_notification_outbox_rule_created
    ON notification_outbox (rule_id, created_at);
CREATE INDEX idx_notification_outbox_event
    ON notification_outbox (event_id);

ALTER TABLE rules ADD CONSTRAINT fk_rules_notification_destination
    FOREIGN KEY (notification_destination_id) REFERENCES notification_destinations(id);
ALTER TABLE rules ADD CONSTRAINT fk_rules_notification_template
    FOREIGN KEY (notification_template_id) REFERENCES notification_templates(id);

CREATE INDEX idx_notification_destinations_channel_enabled
    ON notification_destinations (channel, enabled, display_name);
CREATE INDEX idx_notification_templates_channel_active
    ON notification_templates (channel, active, name, version);
