CREATE TABLE api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    key_hash varchar(64) NOT NULL UNIQUE,
    prefix varchar(32) NOT NULL,
    allowed_event_types jsonb,
    allowed_sources jsonb,
    active boolean NOT NULL,
    expires_at timestamptz,
    created_at timestamptz NOT NULL
);

CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(100) NOT NULL,
    source varchar(100) NOT NULL,
    occurred_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    data jsonb NOT NULL,
    api_key_id bigint REFERENCES api_keys(id)
);

CREATE TABLE rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    rule_type varchar(20) NOT NULL,
    action varchar(20) NOT NULL,
    callback_url text,
    cooldown_seconds integer,
    trigger_mode varchar(20),
    event_type varchar(100) NOT NULL,
    source varchar(100) NOT NULL,
    condition_script text NOT NULL,
    window_seconds integer,
    agg_type varchar(20),
    agg_field varchar(200),
    group_by varchar(200),
    threshold double precision NOT NULL,
    active boolean NOT NULL,
    revision integer NOT NULL DEFAULT 1,
    archived_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uk_rules_name UNIQUE (name),
    CONSTRAINT rules_rule_type_check CHECK (rule_type IN ('CONDITION', 'AGGREGATE')),
    CONSTRAINT rules_action_check CHECK (action IN ('LOG', 'WEBHOOK')),
    CONSTRAINT rules_agg_type_check CHECK (agg_type IS NULL OR agg_type IN ('COUNT', 'SUM', 'AVG', 'MIN', 'MAX')),
    CONSTRAINT rules_trigger_mode_check CHECK (trigger_mode IS NULL OR trigger_mode IN ('EVERY_MATCH', 'EDGE', 'ONCE_PER_WINDOW'))
);

CREATE TABLE rule_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id),
    event_id bigint NOT NULL REFERENCES events(id),
    value double precision,
    group_key varchar(500),
    rule_revision integer NOT NULL DEFAULT 1,
    occurred_at timestamptz NOT NULL
);

CREATE TABLE event_idempotency (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key_id bigint NOT NULL REFERENCES api_keys(id),
    idempotency_key varchar(255) NOT NULL,
    request_hash varchar(64) NOT NULL,
    event_id bigint REFERENCES events(id),
    response_payload jsonb,
    status varchar(20) NOT NULL CHECK (status IN ('PROCESSING', 'COMPLETED')),
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    CONSTRAINT uk_event_idempotency_api_key_key UNIQUE (api_key_id, idempotency_key)
);

CREATE TABLE rule_action_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id),
    rule_revision integer NOT NULL DEFAULT 1,
    scope_key varchar(500) NOT NULL,
    last_successful_delivery_at timestamptz,
    last_matched boolean,
    pending_outbox_id bigint,
    CONSTRAINT uk_rule_action_state_rule_revision_scope
        UNIQUE (rule_id, rule_revision, scope_key)
);

CREATE TABLE rule_action_windows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id),
    rule_revision integer NOT NULL DEFAULT 1,
    scope_key varchar(500) NOT NULL,
    window_start timestamptz NOT NULL,
    delivered_at timestamptz,
    pending_outbox_id bigint,
    CONSTRAINT uk_rule_action_window_rule_revision_scope_start
        UNIQUE (rule_id, rule_revision, scope_key, window_start)
);

CREATE TABLE webhook_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES events(id),
    rule_id bigint,
    rule_revision integer NOT NULL DEFAULT 1,
    rule_name varchar(100) NOT NULL,
    callback_url text NOT NULL,
    payload jsonb NOT NULL,
    scope_key varchar(500) NOT NULL,
    trigger_mode varchar(20) NOT NULL CHECK (trigger_mode IN ('EVERY_MATCH', 'EDGE', 'ONCE_PER_WINDOW')),
    window_start timestamptz,
    deduplication_key varchar(1000) NOT NULL,
    status varchar(30) NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY_SCHEDULED', 'DELIVERED', 'DEAD_LETTER')),
    attempt_count integer NOT NULL,
    next_attempt_at timestamptz NOT NULL,
    last_attempt_at timestamptz,
    delivered_at timestamptz,
    last_error text,
    last_status_code integer,
    manually_retried_at timestamptz,
    lease_token varchar(36),
    lease_expires_at timestamptz,
    cooldown_seconds integer,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uk_webhook_outbox_deduplication_key UNIQUE (deduplication_key)
);

CREATE TABLE rule_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id) ON DELETE RESTRICT,
    revision integer NOT NULL,
    change_type varchar(20) NOT NULL,
    actor varchar(100) NOT NULL,
    changed_at timestamptz NOT NULL DEFAULT now(),
    restored_from_revision integer,
    snapshot_schema_version integer NOT NULL DEFAULT 1,
    snapshot jsonb NOT NULL,
    CONSTRAINT uk_rule_revisions_rule_revision UNIQUE (rule_id, revision)
);

CREATE INDEX idx_events_occurred ON events (occurred_at, id);
CREATE INDEX idx_events_received ON events (received_at, id);
CREATE INDEX idx_rules_active_route ON rules (event_type, source, active) WHERE archived_at IS NULL;
CREATE INDEX idx_rule_events_rule_occurred ON rule_events (rule_id, occurred_at);
CREATE INDEX idx_rule_events_rule_group_occurred ON rule_events (rule_id, group_key, occurred_at);
CREATE INDEX idx_rule_events_rule_revision_group_occurred
    ON rule_events (rule_id, rule_revision, group_key, occurred_at);
CREATE INDEX idx_event_idempotency_created_at ON event_idempotency (created_at);
CREATE INDEX idx_rule_revisions_rule_changed ON rule_revisions (rule_id, changed_at);
CREATE INDEX idx_webhook_outbox_status_next_attempt ON webhook_outbox (status, next_attempt_at, id);
CREATE INDEX idx_webhook_outbox_rule_created ON webhook_outbox (rule_id, created_at);
CREATE INDEX idx_webhook_outbox_rule_revision_created ON webhook_outbox (rule_id, rule_revision, created_at);
CREATE INDEX idx_webhook_outbox_event ON webhook_outbox (event_id);
