ALTER TABLE rules ALTER COLUMN event_type DROP NOT NULL;
ALTER TABLE rules ALTER COLUMN source DROP NOT NULL;
ALTER TABLE rules ALTER COLUMN condition_script DROP NOT NULL;

ALTER TABLE rules DROP CONSTRAINT IF EXISTS rules_rule_type_check;
ALTER TABLE rules ADD CONSTRAINT rules_rule_type_check
    CHECK (rule_type IN ('CONDITION', 'AGGREGATE', 'SEQUENCE'));

CREATE TABLE rule_sequence_steps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id) ON DELETE CASCADE,
    position integer NOT NULL,
    event_type varchar(100) NOT NULL,
    source varchar(100) NOT NULL,
    condition_script text NOT NULL,
    CONSTRAINT uk_rule_sequence_steps_rule_position UNIQUE (rule_id, position),
    CONSTRAINT rule_sequence_steps_position_check CHECK (position BETWEEN 1 AND 5)
);

CREATE TABLE rule_sequence_instances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id) ON DELETE CASCADE,
    rule_revision integer NOT NULL,
    scope_key varchar(500) NOT NULL,
    next_step_position integer,
    status varchar(20) NOT NULL,
    started_at timestamptz NOT NULL,
    last_occurred_at timestamptz NOT NULL,
    last_event_id bigint NOT NULL REFERENCES events(id),
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT rule_sequence_instances_status_check
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT rule_sequence_instances_next_step_check
        CHECK (next_step_position IS NULL OR next_step_position BETWEEN 2 AND 5)
);

CREATE TABLE rule_sequence_instance_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id bigint NOT NULL REFERENCES rule_sequence_instances(id) ON DELETE CASCADE,
    event_id bigint NOT NULL REFERENCES events(id),
    step_position integer NOT NULL,
    occurred_at timestamptz NOT NULL,
    CONSTRAINT uk_rule_sequence_instance_events_instance_position
        UNIQUE (instance_id, step_position),
    CONSTRAINT rule_sequence_instance_events_position_check
        CHECK (step_position BETWEEN 1 AND 5)
);

CREATE INDEX idx_rule_sequence_steps_route
    ON rule_sequence_steps (event_type, source, rule_id, position);
CREATE INDEX idx_rule_sequence_instances_claim
    ON rule_sequence_instances
        (rule_id, rule_revision, scope_key, status, next_step_position, started_at, id);
CREATE INDEX idx_rule_sequence_instances_rule_status
    ON rule_sequence_instances (rule_id, status, created_at);
CREATE INDEX idx_rule_sequence_instance_events_event
    ON rule_sequence_instance_events (event_id);
