ALTER TABLE events ADD COLUMN IF NOT EXISTS processing_trace_version smallint;
ALTER TABLE events ADD COLUMN IF NOT EXISTS matched_rule_count integer;
ALTER TABLE events ADD COLUMN IF NOT EXISTS queued_action_count integer;
ALTER TABLE events ADD COLUMN IF NOT EXISTS suppressed_action_count integer;

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_trace_counts_check;
ALTER TABLE events ADD CONSTRAINT events_trace_counts_check CHECK (
    (matched_rule_count IS NULL OR matched_rule_count >= 0)
    AND (queued_action_count IS NULL OR queued_action_count >= 0)
    AND (suppressed_action_count IS NULL OR suppressed_action_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_events_type_source_received
    ON events (type, source, received_at, id);
CREATE INDEX IF NOT EXISTS idx_events_api_key_received
    ON events (api_key_id, received_at, id);

CREATE TABLE IF NOT EXISTS event_rule_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    rule_id bigint NOT NULL,
    rule_revision integer NOT NULL DEFAULT 1,
    rule_name varchar(100) NOT NULL,
    rule_type varchar(20) NOT NULL CHECK (rule_type IN ('CONDITION', 'AGGREGATE', 'SEQUENCE')),
    group_key varchar(500),
    aggregate_result jsonb,
    sequence_result jsonb,
    action_outcome varchar(30) NOT NULL CHECK (
        action_outcome IN ('LOG_ONLY', 'WEBHOOK_QUEUED', 'WEBHOOK_SUPPRESSED')
    ),
    suppression_reason varchar(80),
    delivery_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_event_rule_outcomes_event_rule_revision
        UNIQUE (event_id, rule_id, rule_revision)
);

CREATE INDEX IF NOT EXISTS idx_event_rule_outcomes_event
    ON event_rule_outcomes (event_id, id);
CREATE INDEX IF NOT EXISTS idx_event_rule_outcomes_delivery
    ON event_rule_outcomes (delivery_id);
