ALTER TABLE events ADD COLUMN IF NOT EXISTS event_time_status varchar(20);
ALTER TABLE events ADD COLUMN IF NOT EXISTS watermark_at_decision timestamptz;

ALTER TABLE events DROP CONSTRAINT IF EXISTS events_event_time_status_check;
ALTER TABLE events ADD CONSTRAINT events_event_time_status_check CHECK (
    event_time_status IS NULL
    OR event_time_status IN ('ON_TIME', 'LATE_ACCEPTED', 'TOO_LATE')
);

CREATE TABLE IF NOT EXISTS event_stream_watermarks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(100) NOT NULL,
    source varchar(100) NOT NULL,
    max_occurred_at timestamptz NOT NULL,
    watermark_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_event_stream_watermarks_source_type UNIQUE (source, event_type)
);

CREATE INDEX IF NOT EXISTS idx_events_event_time_status_received
    ON events (event_time_status, received_at, id);
CREATE INDEX IF NOT EXISTS idx_event_stream_watermarks_updated
    ON event_stream_watermarks (updated_at, id);
