ALTER TABLE rules
    ADD COLUMN IF NOT EXISTS expected_event_type varchar(100),
    ADD COLUMN IF NOT EXISTS expected_source varchar(100),
    ADD COLUMN IF NOT EXISTS expected_condition_script text;

ALTER TABLE rules DROP CONSTRAINT IF EXISTS rules_rule_type_check;
ALTER TABLE rules ADD CONSTRAINT rules_rule_type_check
    CHECK (rule_type IN ('CONDITION', 'AGGREGATE', 'SEQUENCE', 'ABSENCE'));

CREATE TABLE rule_absence_instances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL REFERENCES rules(id) ON DELETE CASCADE,
    rule_revision integer NOT NULL,
    scope_key varchar(500) NOT NULL,
    start_event_id bigint NOT NULL REFERENCES events(id),
    start_occurred_at timestamptz NOT NULL,
    deadline_at timestamptz NOT NULL,
    status varchar(20) NOT NULL,
    resolved_by_event_id bigint REFERENCES events(id),
    resolved_at timestamptz,
    delivery_id bigint,
    suppression_reason varchar(80),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT rule_absence_instances_status_check
        CHECK (status IN ('PENDING', 'SATISFIED', 'TRIGGERED', 'CANCELLED'))
);

CREATE UNIQUE INDEX uk_rule_absence_instances_pending_scope
    ON rule_absence_instances (rule_id, rule_revision, scope_key)
    WHERE status = 'PENDING';
CREATE INDEX idx_rule_absence_instances_due
    ON rule_absence_instances (status, deadline_at, id);
CREATE INDEX idx_rule_absence_instances_satisfaction
    ON rule_absence_instances
        (rule_id, rule_revision, scope_key, status, start_occurred_at, deadline_at);
CREATE INDEX idx_rule_absence_instances_start_event
    ON rule_absence_instances (start_event_id, id);
CREATE INDEX idx_rule_absence_instances_resolved_event
    ON rule_absence_instances (resolved_by_event_id, id);

ALTER TABLE event_rule_outcomes
    ADD COLUMN IF NOT EXISTS absence_result jsonb;

ALTER TABLE event_rule_outcomes DROP CONSTRAINT IF EXISTS event_rule_outcomes_rule_type_check;
ALTER TABLE event_rule_outcomes ADD CONSTRAINT event_rule_outcomes_rule_type_check
    CHECK (rule_type IN ('CONDITION', 'AGGREGATE', 'SEQUENCE', 'ABSENCE'));
